### ISSUE TITLE
TypeError: Cannot set property 'bundlingJavaScript' of undefined

### ISSUE THREAD

**Issue by hofmannsven** [pixelcollective/laravel-mix-wp-blocks#6]
I get the following error in my project (based on the `roots/sage` [10.x branch](https://github.com/roots/sage/tree/10.0.0-dev)):

```
→ npx mix
[webpack-cli] TypeError: Cannot set property 'bundlingJavaScript' of undefined
    at Block.register (node_modules/laravel-mix/src/components/JavaScript.js:36:41)
    at Block.register (node_modules/@tinypixelco/laravel-mix-wp-blocks/index.js:51:11)
    at Object.components.<computed> [as blocks] (node_modules/laravel-mix/src/components/ComponentRegistrar.js:163:49)
    at Object.<anonymous> (webpack.mix.js:32:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

My settings in the [`webpack.mix.js`](https://github.com/roots/sage/blob/10.0.0-dev/webpack.mix.js) file are identical to `roots/sage` settings (again, 10.x branch).

In the devDependencies I'm using the latest version of your package and the latest version of Laravel Mix:
```json
"devDependencies": {
  "@tinypixelco/laravel-mix-wp-blocks": "^1.1.0",
  "laravel-mix": "^6.0.19"
}
```

I've tried to compile it on two different versions of Node (v14.15.4 and v16.14.0) and I get the same error on both of them.

Hope you can help!

**Comment by andrezrv** [comment]
I had the same problem. Turns out npm was installing Laravel Mix v6.0.43, and apparently something about that version is not compatible with this library (or viceversa). Setting `"laravel-mix": "6.0.42"` in my `package.json` solved it for me.

**Comment by cam-vanorman** [comment]
Also running into the same error @hofmannsven and @andrezrv. 

## Details
- Node versions: Tested in `v12.20.1` and `v16.13.1`
- Package versions: `laravel-mix-wp-blocks/1.1.0`, `laravel-mix/6.0.42`

## Log Output

From `npm run build:production` output:
```sh
> mix
> webpack --progress --config=node_modules/laravel-mix/setup/webpack.config.js

[webpack-cli] TypeError: Cannot set properties of undefined (setting 'bundlingJavaScript')
    at Block.register (node_modules/laravel-mix/src/components/JavaScript.js:36:41)
    at Block.register (node_modules/@tinypixelco/laravel-mix-wp-blocks/index.js:51:11)
    at Object.components.<computed> [as blocks] (node_modules/laravel-mix/src/components/ComponentRegistrar.js:163:49)
    at Object.<anonymous> (webpack.mix.js:94:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
ERROR: "mix" exited with 2.
```

**Comment by davideprevosto** [comment]
@andrezrv @cam-vanorman @hofmannsven

I am using "laravel-mix": "^6.0.43" too, and unfortunately I am not an expert, but I was able to solve (for my case), adding a constructor ad the top of the extension Class.

```
constructor() {
    super();
    this.context = Mix
}
```

The full code:

```
const mix = require('laravel-mix')
const JavaScript = require('laravel-mix/src/components/JavaScript')
const DependencyExtractionPlugin = require('@wordpress/dependency-extraction-webpack-plugin')

/**
 * Laravel Mix WP Block
 *
 * @see https://laravel-mix.com/docs/5.0/extending-mix
 * @see https://www.npmjs.com/package/@wordpress/dependency-extraction-webpack-plugin
 */
class Block extends JavaScript {

  constructor() {
    super();
    this.context = Mix
  }

  name() {
    return ['blocks', 'block']
  }
  /**
   * All dependencies that should be installed by Mix.
   *
   * @return {array}
   */
  dependencies() {
    this.requiresReload = `
      Dependencies have been installed. Please run again.
    `

    return [
      '@wordpress/babel-preset-default',
      '@wordpress/dependency-extraction-webpack-plugin',
    ]
  }

  /**
   * Register the plugin component.
   *
   * @param  {string} entry
   * @param  {string} output
   * @param  {object} options
   * @return {void}
   */
  register(entry, output, options = {}) {
    this.pluginOptions = (
      options.disableRegenerator === true ? {
        ...options,
        requestToExternal: function(request) {
          if (request === '@babel/runtime/regenerator') {
            return null
          }
        },
      } : options
    )

    super.register(entry, output)
  }

  /**
   * Plugins to be merged with the master webpack config.
   *
   * @return {array|object}
   */
  webpackPlugins() {
    return new DependencyExtractionPlugin({
      ...this.pluginOptions,
    })
  }

  /**
   * Babel config to be merged with the master Babel config.
   *
   * @return {object}
   */
  babelConfig() {
    return {
      presets: ['@wordpress/babel-preset-default'],
    }
  }
}

mix.extend('block', new Block())
mix.extend('blocks', new Block())
```

I really don't know if this could be a solution, but it is working for me.
